//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HeladeriaContext : DbContext
    {
        public HeladeriaContext()
            : base("name=HeladeriaContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<T_accesos> T_accesos { get; set; }
        public virtual DbSet<T_anulaciones> T_anulaciones { get; set; }
        public virtual DbSet<T_detalle_factura> T_detalle_factura { get; set; }
        public virtual DbSet<T_facturas> T_facturas { get; set; }
        public virtual DbSet<T_productos> T_productos { get; set; }
        public virtual DbSet<T_proveedores> T_proveedores { get; set; }
        public virtual DbSet<T_usuarios> T_usuarios { get; set; }
    }
}
