//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_accesos
    {
        public int id_acceso { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public int usuario_id { get; set; }
    
        public virtual T_usuarios T_usuarios { get; set; }
    }
}
