//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_anulaciones
    {
        public int id_anulacion { get; set; }
        public System.DateTime fecha { get; set; }
        public string comentario { get; set; }
        public int factura_numero { get; set; }
        public int persona_id { get; set; }
    
        public virtual T_facturas T_facturas { get; set; }
        public virtual T_personas T_personas { get; set; }
    }
}
