//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Consultas
    {
        public int idConsulta { get; set; }
        public string consulta { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
    }
}
