//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_detalle_factura
    {
        public int id_detalle_factura { get; set; }
        public int factura_numero { get; set; }
        public int cantidad { get; set; }
        public double precio { get; set; }
        public int producto_codigo { get; set; }
    
        public virtual T_facturas T_facturas { get; set; }
        public virtual T_productos T_productos { get; set; }
    }
}
