//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_facturas()
        {
            this.T_anulaciones = new HashSet<T_anulaciones>();
            this.T_detalle_factura = new HashSet<T_detalle_factura>();
        }
    
        public int numero_factura { get; set; }
        public string nombre { get; set; }
        public double total { get; set; }
        public Nullable<double> descuento { get; set; }
        public System.DateTime fecha { get; set; }
        public int usuario_id { get; set; }
        public int producto_codigo { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_anulaciones> T_anulaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_detalle_factura> T_detalle_factura { get; set; }
        public virtual T_productos T_productos { get; set; }
        public virtual T_usuarios T_usuarios { get; set; }
    }
}
