//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_facturas()
        {
            this.T_anulaciones = new HashSet<T_anulaciones>();
            this.T_detalle_factura = new HashSet<T_detalle_factura>();
        }
    
        public int numero_factura { get; set; }
        public double total { get; set; }
        public Nullable<double> descuento { get; set; }
        public System.DateTime fecha { get; set; }
        public int persona_id { get; set; }
        public string estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_anulaciones> T_anulaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_detalle_factura> T_detalle_factura { get; set; }
        public virtual T_personas T_personas { get; set; }
    }
}
