//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BackEnd.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_productos()
        {
            this.T_detalle_factura = new HashSet<T_detalle_factura>();
        }
    
        public int codigo { get; set; }
        public string categoria { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public double precio { get; set; }
        public System.DateTime fecha_ingreso { get; set; }
        public System.DateTime fecha_vencimiento { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string estado { get; set; }
        public int proveedor_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_detalle_factura> T_detalle_factura { get; set; }
        public virtual T_proveedores T_proveedores { get; set; }
    }
}
